codecov:
  branch: develop
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no
    project:
      default:
        # basic
        target: auto
        threshold: null
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

